/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

/**
 *
 * @author Administrator
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JLabel();
        LogOutBtn = new javax.swing.JLabel();
<<<<<<< HEAD
        ProductsBtn = new javax.swing.JLabel();
        SellersBtn = new javax.swing.JLabel();
        CategoryBtn = new javax.swing.JLabel();
        UpdateAdminBtn = new javax.swing.JLabel();
        CategoryBtn1 = new javax.swing.JLabel();
=======
        SellersBtn = new javax.swing.JLabel();
        StorekeeperBtn = new javax.swing.JLabel();
        UpdateAdminBtn = new javax.swing.JLabel();
        SellerBillBtn = new javax.swing.JLabel();
        ImportBillBtn = new javax.swing.JLabel();
>>>>>>> 1bd4629 (first commit)

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 255));
        jLabel8.setText("ADMIN MENU");

        ExitBtn.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 204, 255));
        ExitBtn.setText("x");
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
        });

        LogOutBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        LogOutBtn.setForeground(new java.awt.Color(255, 204, 255));
        LogOutBtn.setText("Log out");
        LogOutBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        LogOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutBtnMouseClicked(evt);
            }
        });

<<<<<<< HEAD
        ProductsBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        ProductsBtn.setForeground(new java.awt.Color(255, 204, 255));
        ProductsBtn.setText("Products");
        ProductsBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        ProductsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsBtnMouseClicked(evt);
            }
        });

=======
>>>>>>> 1bd4629 (first commit)
        SellersBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        SellersBtn.setForeground(new java.awt.Color(255, 204, 255));
        SellersBtn.setText("Sellers");
        SellersBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        SellersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellersBtnMouseClicked(evt);
            }
        });

<<<<<<< HEAD
        CategoryBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        CategoryBtn.setForeground(new java.awt.Color(255, 204, 255));
        CategoryBtn.setText("Category");
        CategoryBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        CategoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryBtnMouseClicked(evt);
=======
        StorekeeperBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        StorekeeperBtn.setForeground(new java.awt.Color(255, 204, 255));
        StorekeeperBtn.setText("Storekeeper");
        StorekeeperBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        StorekeeperBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StorekeeperBtnMouseClicked(evt);
>>>>>>> 1bd4629 (first commit)
            }
        });

        UpdateAdminBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        UpdateAdminBtn.setForeground(new java.awt.Color(255, 204, 255));
        UpdateAdminBtn.setText("Update account");
        UpdateAdminBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        UpdateAdminBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateAdminBtnMouseClicked(evt);
            }
        });

<<<<<<< HEAD
        CategoryBtn1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        CategoryBtn1.setForeground(new java.awt.Color(255, 204, 255));
        CategoryBtn1.setText("Seller Bill");
        CategoryBtn1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        CategoryBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryBtn1MouseClicked(evt);
=======
        SellerBillBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        SellerBillBtn.setForeground(new java.awt.Color(255, 204, 255));
        SellerBillBtn.setText("Seller Bill");
        SellerBillBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        SellerBillBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellerBillBtnMouseClicked(evt);
            }
        });

        ImportBillBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        ImportBillBtn.setForeground(new java.awt.Color(255, 204, 255));
        ImportBillBtn.setText("Import Bill");
        ImportBillBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        ImportBillBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportBillBtnMouseClicked(evt);
>>>>>>> 1bd4629 (first commit)
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                    .addComponent(CategoryBtn1)
                    .addComponent(SellersBtn)
                    .addComponent(ProductsBtn)
                    .addComponent(LogOutBtn)
                    .addComponent(CategoryBtn)
=======
                    .addComponent(ImportBillBtn)
                    .addComponent(SellerBillBtn)
                    .addComponent(SellersBtn)
                    .addComponent(LogOutBtn)
                    .addComponent(StorekeeperBtn)
>>>>>>> 1bd4629 (first commit)
                    .addComponent(UpdateAdminBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(163, 163, 163)
                        .addComponent(ExitBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExitBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)))
<<<<<<< HEAD
                .addGap(28, 28, 28)
                .addComponent(ProductsBtn)
                .addGap(32, 32, 32)
                .addComponent(SellersBtn)
                .addGap(36, 36, 36)
                .addComponent(CategoryBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(CategoryBtn1)
                .addGap(26, 26, 26)
                .addComponent(UpdateAdminBtn)
                .addGap(35, 35, 35)
                .addComponent(LogOutBtn)
                .addGap(35, 35, 35))
=======
                .addGap(27, 27, 27)
                .addComponent(StorekeeperBtn)
                .addGap(26, 26, 26)
                .addComponent(SellersBtn)
                .addGap(36, 36, 36)
                .addComponent(SellerBillBtn)
                .addGap(30, 30, 30)
                .addComponent(ImportBillBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(UpdateAdminBtn)
                .addGap(43, 43, 43)
                .addComponent(LogOutBtn)
                .addGap(26, 26, 26))
>>>>>>> 1bd4629 (first commit)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void LogOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnMouseClicked
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutBtnMouseClicked

<<<<<<< HEAD
    private void ProductsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsBtnMouseClicked
        new Products().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductsBtnMouseClicked

=======
>>>>>>> 1bd4629 (first commit)
    private void SellersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellersBtnMouseClicked
        new Seller().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellersBtnMouseClicked

<<<<<<< HEAD
    private void CategoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryBtnMouseClicked
        new Category().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CategoryBtnMouseClicked
=======
    private void StorekeeperBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StorekeeperBtnMouseClicked
        new Storekeeper().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StorekeeperBtnMouseClicked
>>>>>>> 1bd4629 (first commit)

    private void UpdateAdminBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateAdminBtnMouseClicked
        new UpdateAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateAdminBtnMouseClicked

<<<<<<< HEAD
    private void CategoryBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryBtn1MouseClicked
        new Seller_Bill().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CategoryBtn1MouseClicked
=======
    private void SellerBillBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellerBillBtnMouseClicked
        new Seller_Bill().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellerBillBtnMouseClicked

    private void ImportBillBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportBillBtnMouseClicked
        new ImportBill().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ImportBillBtnMouseClicked
>>>>>>> 1bd4629 (first commit)

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JLabel CategoryBtn;
    private javax.swing.JLabel CategoryBtn1;
    private javax.swing.JLabel ExitBtn;
    private javax.swing.JLabel LogOutBtn;
    private javax.swing.JLabel ProductsBtn;
    private javax.swing.JLabel SellersBtn;
=======
    private javax.swing.JLabel ExitBtn;
    private javax.swing.JLabel ImportBillBtn;
    private javax.swing.JLabel LogOutBtn;
    private javax.swing.JLabel SellerBillBtn;
    private javax.swing.JLabel SellersBtn;
    private javax.swing.JLabel StorekeeperBtn;
>>>>>>> 1bd4629 (first commit)
    private javax.swing.JLabel UpdateAdminBtn;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
