/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

/**
 *
 * @author Administrator
 */
public class StorekeeperMenu extends javax.swing.JFrame {

    /**
     * Creates new form StorekeeperMenu
     */
    private String account;
    public StorekeeperMenu(String account) {
        this.account = account;
        initComponents();
        HelloLabel.setText("Hello "+this.account+"!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JLabel();
        LogOutBtn = new javax.swing.JLabel();
        ProdBtn = new javax.swing.JLabel();
        UpdateSkBtn = new javax.swing.JLabel();
        HelloLabel = new javax.swing.JLabel();
        CatBtn = new javax.swing.JLabel();
        ImportProdBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 255));
        jLabel8.setText("STOREKEEPER MENU");

        ExitBtn.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 204, 255));
        ExitBtn.setText("x");
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
        });

        LogOutBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        LogOutBtn.setForeground(new java.awt.Color(255, 204, 255));
        LogOutBtn.setText("Log out");
        LogOutBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        LogOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutBtnMouseClicked(evt);
            }
        });

        ProdBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        ProdBtn.setForeground(new java.awt.Color(255, 204, 255));
        ProdBtn.setText("Product");
        ProdBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        ProdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdBtnMouseClicked(evt);
            }
        });

        UpdateSkBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        UpdateSkBtn.setForeground(new java.awt.Color(255, 204, 255));
        UpdateSkBtn.setText("Update account");
        UpdateSkBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        UpdateSkBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateSkBtnMouseClicked(evt);
            }
        });

        HelloLabel.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        HelloLabel.setForeground(new java.awt.Color(255, 204, 255));
        HelloLabel.setText("Hello");

        CatBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        CatBtn.setForeground(new java.awt.Color(255, 204, 255));
        CatBtn.setText("Category");
        CatBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        CatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatBtnMouseClicked(evt);
            }
        });

        ImportProdBtn.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        ImportProdBtn.setForeground(new java.awt.Color(255, 204, 255));
        ImportProdBtn.setText("Import product");
        ImportProdBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        ImportProdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportProdBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImportProdBtn)
                    .addComponent(CatBtn)
                    .addComponent(HelloLabel)
                    .addComponent(ProdBtn)
                    .addComponent(LogOutBtn)
                    .addComponent(UpdateSkBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(163, 163, 163)
                        .addComponent(ExitBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExitBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(HelloLabel)
                .addGap(33, 33, 33)
                .addComponent(ProdBtn)
                .addGap(42, 42, 42)
                .addComponent(CatBtn)
                .addGap(35, 35, 35)
                .addComponent(ImportProdBtn)
                .addGap(34, 34, 34)
                .addComponent(UpdateSkBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(LogOutBtn)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void LogOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnMouseClicked
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutBtnMouseClicked

    private void ProdBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdBtnMouseClicked
        new Products(this.account).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProdBtnMouseClicked

    private void UpdateSkBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateSkBtnMouseClicked
        new UpdateStorekeeper(this.account).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateSkBtnMouseClicked

    private void CatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatBtnMouseClicked
        new Category(this.account).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CatBtnMouseClicked

    private void ImportProdBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportProdBtnMouseClicked
        new ImportProduct(this.account).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ImportProdBtnMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StorekeeperMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StorekeeperMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StorekeeperMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StorekeeperMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StorekeeperMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CatBtn;
    private javax.swing.JLabel ExitBtn;
    private javax.swing.JLabel HelloLabel;
    private javax.swing.JLabel ImportProdBtn;
    private javax.swing.JLabel LogOutBtn;
    private javax.swing.JLabel ProdBtn;
    private javax.swing.JLabel UpdateSkBtn;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
